model_name: "EleutherAI/gpt-neo-125M"
batch_size: 8
num_epochs: 20
num_experts: 6
learning_rate: 0.000001
device: "cuda"
save_dir: "./checkpoints"
trainer_id: "buffer-training-64"
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
selection_temperature: 1
early_stopping_patience: 20
buffer_batch_size: 4
