model_name: "EleutherAI/gpt-neo-125M"
batch_size: 1
num_epochs: 10
num_experts: 8
learning_rate: 0.000001
device: "cuda"
save_dir: "./checkpoints"
trainer_id: "exp8-lr10-6-temp0.05-epoch10"
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
selection_temperature: 0.05
early_stopping_patience: 10
