model_name: "EleutherAI/gpt-neo-125M"
batch_size: 10
num_epochs: 3
num_experts: 2
learning_rate: 0.0001
device: "cpu"
save_dir: "./checkpoints"
trainer_id: "debug-run-multiple-experts"
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
selection_temperature: 3.0
early_stopping_patience: 2
