model_name: "EleutherAI/gpt-neo-125M"
batch_size: 8
num_epochs: 10
num_experts: 6
learning_rate: 0.0001
device: "cuda"
save_dir: "./checkpoints"
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
selection_temperature: 3.0
early_stopping_patience: 5
