model_name: "EleutherAI/gpt-neo-125M"
batch_size: 8
num_epochs: 10
num_experts: 4
learning_rate: 0.00001
device: "cuda"
save_dir: "./checkpoints"
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
selection_temperature: 5.0
early_stopping_patience: 5
